management.endpoint.shutdown.enabled: true
management.endpoints.web.base-path: /olx-advertise
management.endpoints.web.exposure.include: '*'
management.health.circuitbreakers.enabled: true
management.endpoint.health.show-details: always

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

resilience4j.circuitbreaker.instances.AUTH_TOKEN_VALIDATION.registeHealthIndicator: true
resilience4j.circuitbreaker.instances.AUTH_TOKEN_VALIDATION.automaticTransitionFromOpenToHalfOpenEnabled: true
resilience4j.circuitbreaker.instances.AUTH_TOKEN_VALIDATION.failureRateThreshold: 50
resilience4j.circuitbreaker.instances.AUTH_TOKEN_VALIDATION.minimumNumberOfCalls: 5
resilience4j.circuitbreaker.instances.AUTH_TOKEN_VALIDATION.permittedNumberOfCallsInHalfOpenState: 3
resilience4j.circuitbreaker.instances.AUTH_TOKEN_VALIDATION.waitDurationInOpenState: 5s
        
server:
  port: 9001

spring.application.name: ADVERTISE-SERVICE
spring.config.import: configserver:http://localhost:9999
spring.zipkin.base-url: http://localhost:9411
spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}